<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>dd5f8916-e2d7-404a-9138-16a1aad795d0</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_team_project_releases</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[2]/nav[1]/ul[1]/li[2]/a[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[title='Planning'] a</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
</WebElementEntity>