<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>994d4255-7ef3-43a3-8d57-ba32bd0f117c</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_team_project_settings</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[2]/nav[1]/ul[1]/li[7]/a[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[title][href='\/team\/264558\/project\/378267\/settings'] a</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
</WebElementEntity>