<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>4a23b1a2-866a-4c44-bd37-b0697407c47f</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_team_project_executions</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]/div[2]/div[1]/ul[1]/a[2]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[href='\/team\/264558\/project\/378267\/executions']</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'page-tab__nav__nav-link tab-button  d-flex align-items-center')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>page-tab__nav__nav-link tab-button  d-flex align-items-center</value>
        <webElementGuid>6616711e-872c-45aa-a224-3132c723df9b</webElementGuid>
    </webElementProperties>
</WebElementEntity>