<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>31069d08-e96c-4f22-ab3b-38bbcbdd0756</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_team_project_test_reports_test_executio</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]/div[2]/div[1]/ul[1]/a[3]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[href='\/team\/264558\/project\/378267\/test-reports\/test-execution\/test-performance']</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'page-tab__nav__nav-link tab-button  d-flex align-items-center')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>page-tab__nav__nav-link tab-button  d-flex align-items-center</value>
        <webElementGuid>9f81c907-7768-4a53-a688-573dfe8bacb9</webElementGuid>
    </webElementProperties>
</WebElementEntity>