<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>429e4b44-a9fe-4f81-b3d0-0bc247502162</elementGuidId>
    <imagePath></imagePath>
    <name>button_settings</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[3]/button[5]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[tabindex][title='Settings']</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'MuiButtonBase-root MuiIconButton-root MuiIconButton-sizeLarge css-resnt5') and equals(@title,'Settings')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>MuiButtonBase-root MuiIconButton-root MuiIconButton-sizeLarge css-resnt5</value>
        <webElementGuid>0d5ebedd-1ffd-43ca-aad6-6bda2e5a7872</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>Settings</value>
        <webElementGuid>f949ddcc-a37f-4aad-9a62-6472c1626020</webElementGuid>
    </webElementProperties>
</WebElementEntity>