<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>d2dde0e1-6c3b-4cfa-b0c2-76b500b82799</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_page_visual_testing_view_setup_doc</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[3]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>.button-setup</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'btn button-setup')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>btn button-setup</value>
        <webElementGuid>3335a477-d763-4a92-b1d7-79d2f9cd9877</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>data-groupid</name>
        <type>Main</type>
        <value>access-report</value>
        <webElementGuid>909cf101-34c0-4f03-a35b-efe5ce5771c0</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>data-trackid</name>
        <type>Main</type>
        <value>page-visual-testing-view-setup-doc</value>
        <webElementGuid>ff60e658-c1ec-463b-b2fd-6b2f812f8797</webElementGuid>
    </webElementProperties>
</WebElementEntity>