<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>3e9142c9-1630-4af9-8851-53d906896571</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_page_visual_testing_view_overview_doc</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[3]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/a[2]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>.button-learn-more</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'btn button-learn-more')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>btn button-learn-more</value>
        <webElementGuid>7489eaaf-b06f-4f96-a3d6-4a5b436f89c2</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>data-groupid</name>
        <type>Main</type>
        <value>access-report</value>
        <webElementGuid>d464b45d-02b9-41a1-9cd2-a645cecbe765</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>data-trackid</name>
        <type>Main</type>
        <value>page-visual-testing-view-overview-doc</value>
        <webElementGuid>cf7d0a50-829f-44b0-86b2-f025c88720d7</webElementGuid>
    </webElementProperties>
</WebElementEntity>