<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>b658d645-1c94-45ba-9c0b-253671668d56</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_team_project_baseline_collection</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[2]/div[1]/li[2]/a[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[title='Visual\ Baseline\ Collections'] a</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
</WebElementEntity>