<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>21ef750e-1e61-4f3c-a1f3-29b3c6d04250</elementGuidId>
    <imagePath></imagePath>
    <name>button_settings</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[3]/button[5]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[tabindex][title='Settings']</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'MuiButtonBase-root MuiIconButton-root MuiIconButton-sizeLarge css-resnt5') and equals(@title,'Settings')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>MuiButtonBase-root MuiIconButton-root MuiIconButton-sizeLarge css-resnt5</value>
        <webElementGuid>249b02a8-feb0-4996-99b7-7640dabbf1d1</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>Settings</value>
        <webElementGuid>0f85b08e-1236-4168-a445-18ca305fd6eb</webElementGuid>
    </webElementProperties>
</WebElementEntity>