<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>8293f06a-e87e-4d0f-ad80-2009de1dbd31</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_connect_git_script_repository</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>.btn-primary</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'btn btn-primary') and equals(@title,'Connect Git Repository')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>btn btn-primary</value>
        <webElementGuid>e2027f9f-26a8-4fd1-87d1-7d50d065d480</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>data-groupid</name>
        <type>Main</type>
        <value>access-configuration</value>
        <webElementGuid>11c46aa8-12d2-4129-b502-c105d9f67146</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>data-trackid</name>
        <type>Main</type>
        <value>connect-git-script-repository</value>
        <webElementGuid>24aa10d5-e5b1-4a2e-8975-ee7d21208120</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>Connect Git Repository</value>
        <webElementGuid>f86bfa35-f7d1-4364-8aea-7c3fd3caa17c</webElementGuid>
    </webElementProperties>
</WebElementEntity>