<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>d9982e94-5aba-4a06-901d-29f47927635c</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_team_project_agent</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[2]/div[1]/li[3]/a[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[title='Test\ Environments'] a</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
</WebElementEntity>