<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>35ecefc1-3440-422d-bc82-00441c9adb38</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_team_project_test_project_1</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[3]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/table[1]/tbody[1]/tr[2]/td[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[href='\/team\/264558\/project\/378267\/test-project\/205278']</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'d-block ')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>d-block </value>
        <webElementGuid>b36257fe-98c1-4da1-8d9d-e994b7bdc78f</webElementGuid>
    </webElementProperties>
</WebElementEntity>