<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>9381a0b6-1263-489a-ae57-202adf90fcb0</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_team_project_test_project</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[3]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/table[1]/tbody[1]/tr[1]/td[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[href='\/team\/264558\/project\/378267\/test-project\/376901']</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'d-block ')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>d-block </value>
        <webElementGuid>bb2c9c40-6b76-48f8-abc1-977d7995e436</webElementGuid>
    </webElementProperties>
</WebElementEntity>