<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>65d17f95-7024-46f7-a6d0-fc7e1f782510</elementGuidId>
    <imagePath></imagePath>
    <name>span_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[1]/div[1]/button[1]/span[2]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#select-organization .MuiButton-endIcon</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'MuiButton-endIcon MuiButton-iconSizeMedium css-pt151d')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>MuiButton-endIcon MuiButton-iconSizeMedium css-pt151d</value>
        <webElementGuid>9ebc6176-275d-4748-b590-dbeffb187fcc</webElementGuid>
    </webElementProperties>
</WebElementEntity>