<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>4c603f08-e6b0-4a28-ba99-2b45afe64749</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_team_project_test_reports_test_maintena_1</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]/div[2]/div[1]/ul[1]/a[2]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[href='\/team\/264558\/project\/378267\/test-reports\/test-maintenance\/stale']</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'page-tab__nav__nav-link tab-button  d-flex align-items-center')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>page-tab__nav__nav-link tab-button  d-flex align-items-center</value>
        <webElementGuid>d329adde-7d54-42b1-8e63-7210a1a6cf9b</webElementGuid>
    </webElementProperties>
</WebElementEntity>