<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>6e632438-0c13-40d5-8cbf-7a6b0e61948a</elementGuidId>
    <imagePath></imagePath>
    <name>button_nghi</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[3]/button[6]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[tabindex][title='Nghi']</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'MuiButtonBase-root MuiIconButton-root MuiIconButton-sizeLarge css-resnt5') and equals(@title,'Nghi')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>MuiButtonBase-root MuiIconButton-root MuiIconButton-sizeLarge css-resnt5</value>
        <webElementGuid>f89863e0-608c-44d2-beeb-cdd60d0a08d4</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>Nghi</value>
        <webElementGuid>671fbee8-f6f9-4fff-b7ca-a159edd5ba1b</webElementGuid>
    </webElementProperties>
</WebElementEntity>