<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>c4581ef3-f76b-4cf0-9d07-726666401203</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_upload_test_run_reports</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[title='Upload\ Reports']</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'btn btn-secondary') and equals(@title,'Upload Reports')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>btn btn-secondary</value>
        <webElementGuid>a40d5a5a-d06a-4464-b8ce-5da6925b367e</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>data-groupid</name>
        <type>Main</type>
        <value>upload-report</value>
        <webElementGuid>e67c3e32-cf69-4b90-a85f-43da95c53ae5</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>data-trackid</name>
        <type>Main</type>
        <value>upload-test-run-reports</value>
        <webElementGuid>19da4326-e34c-46e1-9dc4-535f1fdf74b6</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>Upload Reports</value>
        <webElementGuid>773c0bea-6dc6-4c04-8dee-77e64d51135f</webElementGuid>
    </webElementProperties>
</WebElementEntity>