<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>dd0d2b6b-4deb-4cce-8aa4-35a264e8c85d</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_team_project_executions_1</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]/div[2]/div[1]/ul[1]/a[2]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>.page-tab__nav__nav-link.active</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'page-tab__nav__nav-link tab-button active d-flex align-items-center active')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>page-tab__nav__nav-link tab-button active d-flex align-items-center active</value>
        <webElementGuid>3ac7f9d3-f76c-4d48-acc3-66c58e23b294</webElementGuid>
    </webElementProperties>
</WebElementEntity>