<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>6f7d4164-29c1-4f49-bb89-4cb9c8b5013c</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_team_project_test_project</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[2]/div[1]/li[2]/a[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[title='Script\ Repositories'] a</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
</WebElementEntity>