<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>8b9995b6-9def-436c-aac2-ddde919fcaae</elementGuidId>
    <imagePath></imagePath>
    <name>button_nghi</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[3]/button[6]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[tabindex][title='Nghi']</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'MuiButtonBase-root MuiIconButton-root MuiIconButton-sizeLarge css-resnt5') and equals(@title,'Nghi')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>MuiButtonBase-root MuiIconButton-root MuiIconButton-sizeLarge css-resnt5</value>
        <webElementGuid>436b6f72-cb79-4984-b4a0-74508862602d</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>Nghi</value>
        <webElementGuid>823c62b6-a3e3-4bdc-bdf3-741227aa65e5</webElementGuid>
    </webElementProperties>
</WebElementEntity>