<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>b48b248a-b4db-4b4d-bd73-40b4e3185272</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_team_project_web_services</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]/div[2]/div[1]/ul[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>.page-tab__nav__nav-link.active</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'page-tab__nav__nav-link tab-button active d-flex align-items-center active')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>page-tab__nav__nav-link tab-button active d-flex align-items-center active</value>
        <webElementGuid>a012cee3-6b2a-43fa-a05d-a62ece97fac7</webElementGuid>
    </webElementProperties>
</WebElementEntity>