<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>ab5180ed-b5c2-4739-8313-6d9f199dca5f</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_team_project_web_services_anomalies</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]/div[2]/div[1]/ul[1]/a[2]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[href='\/team\/264558\/project\/378267\/web-services-anomalies']</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'page-tab__nav__nav-link tab-button  d-flex align-items-center')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>page-tab__nav__nav-link tab-button  d-flex align-items-center</value>
        <webElementGuid>66bf6669-25e7-4fbf-9864-e2c8ce113c2b</webElementGuid>
    </webElementProperties>
</WebElementEntity>