<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>c8953817-d62d-420a-a411-dd9156f24717</elementGuidId>
    <imagePath></imagePath>
    <name>button_open_schedule_dialog</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[2]/div[3]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#open-schedule-dialog</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'open-schedule-dialog') and equals(@class,'btn btn-primary') and equals(@title,'Schedule Test Run')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>btn btn-primary</value>
        <webElementGuid>779d79b6-86f2-44de-bdcb-36979c01b9eb</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>open-schedule-dialog</value>
        <webElementGuid>6ded1bb2-75f3-4709-a6ef-a7a48041e259</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>Schedule Test Run</value>
        <webElementGuid>4746258e-fd3c-419c-b3a4-55d0bd20e541</webElementGuid>
    </webElementProperties>
</WebElementEntity>