<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>bda4e001-25d5-4f06-9af3-412a2eb3c8b4</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_team_project_grid</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[2]/div[2]/div[1]/li[2]/a[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[title='Test\ Schedules'] a</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
</WebElementEntity>