<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>4d69c843-9623-4802-ad81-1de3b1bea20a</elementGuidId>
    <imagePath></imagePath>
    <name>span_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[1]/div[1]/button[1]/span[2]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>.MuiButton-endIcon</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'MuiButton-endIcon MuiButton-iconSizeMedium css-pt151d')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>MuiButton-endIcon MuiButton-iconSizeMedium css-pt151d</value>
        <webElementGuid>f8586028-d2c9-412a-ab9e-c0130504ff7e</webElementGuid>
    </webElementProperties>
</WebElementEntity>