<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>19f12d56-f43b-4e69-b414-8ca116080ba1</elementGuidId>
    <imagePath></imagePath>
    <name>button_nghi</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[3]/button[6]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[tabindex][title='Nghi']</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'MuiButtonBase-root MuiIconButton-root MuiIconButton-sizeLarge css-resnt5') and equals(@title,'Nghi')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>MuiButtonBase-root MuiIconButton-root MuiIconButton-sizeLarge css-resnt5</value>
        <webElementGuid>84ebe9bf-dd71-4339-8e89-6d6d3bce51ce</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>Nghi</value>
        <webElementGuid>7f39a9ac-a5bd-4cae-b8e6-7aeb7bf7d21d</webElementGuid>
    </webElementProperties>
</WebElementEntity>