<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>9cda10e8-9566-45b9-84b4-780903efb371</elementGuidId>
    <imagePath></imagePath>
    <name>div_react_select_2_option_0</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[3]/div[1]/div[2]/div[1]/div[2]/div[1]/div[2]/div[1]/div[2]/div[1]/div[2]/div[1]/div[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#react-select-2-option-0</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'react-select-2-option-0') and equals(@class,'react-select__option css-yt9ioa-option')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>react-select__option css-yt9ioa-option</value>
        <webElementGuid>7fa207d1-2bf8-4902-aac0-9f2e148cad4b</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>react-select-2-option-0</value>
        <webElementGuid>f7bf8054-ff3e-4904-bc12-64079e636dbe</webElementGuid>
    </webElementProperties>
</WebElementEntity>