<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>a4529200-5be0-4867-a70c-bbf7d4f832e6</elementGuidId>
    <imagePath></imagePath>
    <name>div_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[3]/div[1]/div[2]/div[1]/div[2]/div[1]/div[2]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>.react-select__indicator</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'react-select__indicator react-select__dropdown-indicator css-tlfecz-indicatorContainer')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>react-select__indicator react-select__dropdown-indicator css-tlfecz-indicatorContainer</value>
        <webElementGuid>bfcc31aa-f2a6-4c51-97ee-266a580f8e72</webElementGuid>
    </webElementProperties>
</WebElementEntity>