<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>8ca65f18-7435-473b-892a-b7a08222d4a3</elementGuidId>
    <imagePath></imagePath>
    <name>button_make_active_release</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[data-trackid='make-active-release']</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'btn btn-secondary')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>btn btn-secondary</value>
        <webElementGuid>c678b30e-9311-4d2a-96ab-d24da6d67e66</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>data-trackid</name>
        <type>Main</type>
        <value>make-active-release</value>
        <webElementGuid>df723707-6ba1-4dc1-8dae-ba39b33fd8a6</webElementGuid>
    </webElementProperties>
</WebElementEntity>