<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>1d3c1d14-87d4-4b6c-befd-4f02841c4b92</elementGuidId>
    <imagePath></imagePath>
    <name>button_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//button[contains(., 'Sort: ')]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>form</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'mt-2')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>mt-2</value>
        <webElementGuid>ab76ebcb-7387-4488-b623-3269e5f69158</webElementGuid>
    </webElementProperties>
</WebElementEntity>