<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>aa3be366-4714-428d-aa4a-0988522b1b4b</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_edit</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/a[3]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[href='\/team\/264558\/project\/378267\/releases\/165531\/edit']</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'btn btn-secondary') and equals(@title,'Edit')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>btn btn-secondary</value>
        <webElementGuid>0ffabad4-a43f-4191-b7ad-0f838214b966</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>Edit</value>
        <webElementGuid>b27acf0f-a7f4-48fc-908f-aff5cb099a0a</webElementGuid>
    </webElementProperties>
</WebElementEntity>