<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>12360975-ca6b-4fde-89fc-f3b6626b9bfc</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_team_project_releases</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[3]/div[1]/div[2]/div[1]/div[2]/div[1]/div[1]/div[2]/table[1]/tbody[1]/tr[3]/td[2]/div[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[href='\/team\/264558\/project\/378267\/releases\/165529']</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'d-block ')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>d-block </value>
        <webElementGuid>f1968b69-d5a8-411e-b74a-8f67f8bae82c</webElementGuid>
    </webElementProperties>
</WebElementEntity>