<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>15d84fe9-e900-43ea-aac6-14911102577a</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_team_project_releases_1</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[3]/div[1]/div[2]/div[1]/div[2]/div[1]/div[1]/div[2]/table[1]/tbody[1]/tr[1]/td[2]/div[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[href='\/team\/264558\/project\/378267\/releases\/165531']</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'d-block ')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>d-block </value>
        <webElementGuid>f1bdebe8-2e78-4f59-ac0d-a24bc9c4a315</webElementGuid>
    </webElementProperties>
</WebElementEntity>