<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>db9ae6dd-7957-44b6-9425-f0ddcb42ed79</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_create_release</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>.btn-secondary</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'btn btn-secondary') and equals(@title,'Create Release')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>btn btn-secondary</value>
        <webElementGuid>8bcbce9c-8ac4-4de0-9b8f-4d7efd6ca33a</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>data-trackid</name>
        <type>Main</type>
        <value>create-release</value>
        <webElementGuid>cf93d5bd-02ec-45ba-8d4d-fca05d0478b5</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>Create Release</value>
        <webElementGuid>9243f0e8-6fea-4c3b-84a0-d2e64c0c1e77</webElementGuid>
    </webElementProperties>
</WebElementEntity>