<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>1ea0b952-5d3c-4098-aac7-6f8241a4f702</elementGuidId>
    <imagePath></imagePath>
    <name>span_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[1]/div[1]/button[1]/span[2]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#select-organization .MuiButton-endIcon</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'MuiButton-endIcon MuiButton-iconSizeMedium css-pt151d')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>MuiButton-endIcon MuiButton-iconSizeMedium css-pt151d</value>
        <webElementGuid>fb71c99c-cf39-4512-8cc0-0ce925d36094</webElementGuid>
    </webElementProperties>
</WebElementEntity>